version: '3.7'
services:
  ol-vsam-qa:
    container_name: ol-vsam-qa
    image: openlegacy/ol-vsam-api:v1.15
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=qa"  
    networks: 
      - ol-vsam-network
    restart: always
  ol-vsam-prod:
    container_name: ol-vsam-prod
    image: openlegacy/ol-vsam-api:v1.15
    ports:
      - "8081:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"  
    networks: 
      - ol-vsam-network
    restart: always
networks:
  ol-vsam-network:
    name: ol-vsam-network
    driver: bridge